Foundation_English = float(input("type grade"))
General_Business = float(input("type grade"))
Introduction_to_computer_system = float(input("type grade"))
computer_programming = float(input("type grade"))
print("your score")
print("Foundation English score", Foundation_English)
print("General business score", General_Business)
print("Introduction to computer system score", Introduction_to_computer_system)
print("computer programming score", computer_programming)