a = float(input("enter first number"))
b = float(input("enter second number"))
c = a + b
print(a, "+", b , "=", c)
d = a - b
print(a, "-", b ,"=", d)
e = a * b
print(a, "*", b , "=", e)
f = a / b
print(a, "/", b , "=", f)